### ISSUE TITLE
Initialize Playlist Issue

### ISSUE THREAD

**Issue by KhoaNguyen01004** [KhoaNguyen01004/Music-Project#14]
In line number [15](https://github.com/KhoaNguyen01004/Music-Project/blob/62f8e6c72bc765ea78de17f16f5564b6d13e7d0a/src/YouTubeHandler.py#L15) on YoutubeHandler class, you implement a method to initialize a playlist. I think it is better to let the user pass in the parameter instead of you passing the default playlist.

So for example, for my playlist initialize method, I allow the user to give the URL link into the parameter instead of initializing it as the default one. This will allow that method to be used with different playlists, not just the default one.

**Comment by CalvinGDuong** [comment]
The playlist initialize method works just fine. If the user passes no arguments, then the default playlist will be active. However, if the user were to pass in another playlist id as an argument to that function, the playlist will change. I have tested it and you can test it out too. You will see that the graph changes depending on what playlist is being used.

**Comment by KhoaNguyen01004** [comment]
Oh I see. I though when we pass stuff inside the argument when initialize, it will only use that. I got it, thanks for explaining.
